[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[digikam-appimage]
source = "anitya"
anitya_id = 437

[bilibili_manga_downloader-bin]
source = "github"
github = "MOMOYATW/bilibili_manga_downloader"
use_latest_release = "true"
prefix = "v"